library(golem)
library(shinydashboard)
library(shinyalert)
library(dplyr)

pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)
options(warn=-1)
options("golem.app.prod" = TRUE)
options(shiny.maxRequestSize=200*1024^2)
Sys.setenv(TZ = "Europe/Berlin")
run_app() # add parameters here (if any)
